version: "3"
services:
  web:
    build: ./
    image: skobara/ssh
    container_name: ssh
    restart: always
    ports:
      - "8003:3000"
    volumes:
      - "./:/usr/src/app"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:geo.gcoos.org;PathPrefix:/ssh"
      - "traefik.port=3000"
      - "traefik.docker.network=geo_net"
    networks:
      - geo_net

networks:
  geo_net:
    external: true
